In [100]:
import numpy as np
import pandas as pd

In [101]:
Mdata=pd.read_csv("matches.csv")
Ddata=pd.read_csv("deliveries.csv")

In [102]:
mdata=Mdata[['id','city','team1','team2','toss_winner','toss_decision','winner','win_by_runs','win_by_wickets',]]

In [103]:
Ddata = Ddata.drop(columns=['fielder', 'dismissal_kind', 'extra_runs', 'batsman_runs', 'penalty_runs', 'legbye_runs', 'bye_runs'])


In [104]:
Ddata=Ddata.drop(columns=['noball_runs','wide_runs'])

In [105]:
totalscore=Ddata.groupby(['match_id','inning']).sum()['total_runs'].reset_index()

In [106]:
d=Ddata

In [107]:
d['ball']=d['ball']+d['over']*6-6
Ddata=d
Ddata=Ddata.drop(columns=['over'])

In [108]:
D1=Ddata[Ddata['inning']==2]
D1['player_dismissed'] = D1['player_dismissed'].apply(lambda x: 0 if pd.isna(x) else 1)
D1['player_dismissed']=D1.groupby(['match_id','inning'])['player_dismissed'].cumsum()


C:\Users\Administrator\AppData\Local\Temp\ipykernel_12616\2033505372.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  D1['player_dismissed'] = D1['player_dismissed'].apply(lambda x: 0 if pd.isna(x) else 1)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_12616\2033505372.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  D1['player_dismissed']=D1.groupby(['match_id','inning'])['player_dismissed'].cumsum()


In [109]:
D1.head()

match_id  inning                 batting_team         bowling_team  ball  \
125         1       2  Royal Challengers Bangalore  Sunrisers Hyderabad     1   
126         1       2  Royal Challengers Bangalore  Sunrisers Hyderabad     2   
127         1       2  Royal Challengers Bangalore  Sunrisers Hyderabad     3   
128         1       2  Royal Challengers Bangalore  Sunrisers Hyderabad     4   
129         1       2  Royal Challengers Bangalore  Sunrisers Hyderabad     5   

           batsman    non_striker   bowler  is_super_over  total_runs  \
125       CH Gayle  Mandeep Singh  A Nehra              0           1   
126  Mandeep Singh       CH Gayle  A Nehra              0           0   
127  Mandeep Singh       CH Gayle  A Nehra              0           0   
128  Mandeep Singh       CH Gayle  A Nehra              0           2   
129  Mandeep Singh       CH Gayle  A Nehra              0           4   

     player_dismissed  
125                 0  
126                 0  
127                 0  
128                 0  
129                 0

In [ ]:
D1.columns

In [110]:
D1=D1.drop(columns=['bowler','batsman','non_striker'])


In [111]:
D1['total_runs']=D1.groupby(['match_id'])['total_runs'].cumsum()
D1=D1[D1['is_super_over']==0]
D1=D1.drop(columns=['is_super_over'])

In [112]:
merged = pd.merge(mdata, D1, left_on='id', right_on='match_id')
merged=merged.drop(columns=['match_id'])
merged=merged.drop(columns=['team1','team2'])
merged=merged[~merged['batting_team'].isin(['Rising Pune Supergiant', 'Pune Warriors','Kochi Tuskers Kerala','Gujarat Lions'])]
merged=merged[~merged['bowling_team'].isin(['Rising Pune Supergiant', 'Gujarat Lions','Pune Warriors','Kochi Tuskers Kerala'])]
merged['toss_winner'] = merged['toss_winner'].str.replace('Delhi Daredevils','Delhi Capitals')
merged['winner'] = merged['winner'].str.replace('Delhi Daredevils','Delhi Capitals')
merged['batting_team'] = merged['batting_team'].str.replace('Delhi Daredevils','Delhi Capitals')
merged['bowling_team'] = merged['bowling_team'].str.replace('Delhi Daredevils','Delhi Capitals')
merged['toss_winner'] = merged['toss_winner'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
merged['winner'] = merged['winner'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
merged['batting_team'] = merged['batting_team'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
merged['bowling_team'] = merged['bowling_team'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [113]:
merged=merged.drop(columns=['toss_decision','toss_winner'])

In [116]:
batting=merged[merged['batting_team']==merged['winner']]

In [117]:
batting

id           city               winner  win_by_runs  win_by_wickets  \
683        7         Mumbai       Mumbai Indians            0               4   
684        7         Mumbai       Mumbai Indians            0               4   
685        7         Mumbai       Mumbai Indians            0               4   
686        7         Mumbai       Mumbai Indians            0               4   
687        7         Mumbai       Mumbai Indians            0               4   
...      ...            ...                  ...          ...             ...   
86111  11414  Visakhapatnam  Chennai Super Kings            0               6   
86112  11414  Visakhapatnam  Chennai Super Kings            0               6   
86113  11414  Visakhapatnam  Chennai Super Kings            0               6   
86114  11414  Visakhapatnam  Chennai Super Kings            0               6   
86115  11414  Visakhapatnam  Chennai Super Kings            0               6   

       inning         batting_team           bowling_team  ball  total_runs  \
683         2       Mumbai Indians  Kolkata Knight Riders     1           0   
684         2       Mumbai Indians  Kolkata Knight Riders     2           0   
685         2       Mumbai Indians  Kolkata Knight Riders     3           4   
686         2       Mumbai Indians  Kolkata Knight Riders     4           4   
687         2       Mumbai Indians  Kolkata Knight Riders     5           5   
...       ...                  ...                    ...   ...         ...   
86111       2  Chennai Super Kings         Delhi Capitals   110         153   
86112       2  Chennai Super Kings         Delhi Capitals   111         153   
86113       2  Chennai Super Kings         Delhi Capitals   112         153   
86114       2  Chennai Super Kings         Delhi Capitals   113         154   
86115       2  Chennai Super Kings         Delhi Capitals   114         162   

       player_dismissed  
683                   0  
684                   0  
685                   0  
686                   0  
687                   0  
...                 ...  
86111                 3  
86112                 3  
86113                 4  
86114                 4  
86115                 4  

[39554 rows x 11 columns]

In [118]:
merged['winner'] = merged.apply(lambda row: 0 if row['batting_team'] == row['winner'] else 1, axis=1)



In [119]:
# batting=merged[merged['winner']==0]

In [ ]:
merged.head()

In [121]:
totalscore=totalscore[totalscore['inning']==1]

In [122]:
totalscore=totalscore.drop(columns=['inning'])

In [123]:
totalscore=totalscore.rename(columns={'total_runs':'target'})

In [140]:
totalscore.head(10)

match_id  target
0          1     207
2          2     184
4          3     183
6          4     163
8          5     157
10         6     135
12         7     178
14         8     148
16         9     205
18        10     158

id           city  winner  win_by_runs  win_by_wickets  inning  \
683        7         Mumbai       0            0               4       2   
684        7         Mumbai       0            0               4       2   
685        7         Mumbai       0            0               4       2   
686        7         Mumbai       0            0               4       2   
687        7         Mumbai       0            0               4       2   
...      ...            ...     ...          ...             ...     ...   
86111  11414  Visakhapatnam       0            0               6       2   
86112  11414  Visakhapatnam       0            0               6       2   
86113  11414  Visakhapatnam       0            0               6       2   
86114  11414  Visakhapatnam       0            0               6       2   
86115  11414  Visakhapatnam       0            0               6       2   

              batting_team           bowling_team  ball  total_runs  \
683         Mumbai Indians  Kolkata Knight Riders     1           0   
684         Mumbai Indians  Kolkata Knight Riders     2           0   
685         Mumbai Indians  Kolkata Knight Riders     3           4   
686         Mumbai Indians  Kolkata Knight Riders     4           4   
687         Mumbai Indians  Kolkata Knight Riders     5           5   
...                    ...                    ...   ...         ...   
86111  Chennai Super Kings         Delhi Capitals   110         153   
86112  Chennai Super Kings         Delhi Capitals   111         153   
86113  Chennai Super Kings         Delhi Capitals   112         153   
86114  Chennai Super Kings         Delhi Capitals   113         154   
86115  Chennai Super Kings         Delhi Capitals   114         162   

       player_dismissed  
683                   0  
684                   0  
685                   0  
686                   0  
687                   0  
...                 ...  
86111                 3  
86112                 3  
86113                 4  
86114                 4  
86115                 4  

[39554 rows x 11 columns]

In [146]:
mergednew = pd.merge(totalscore,merged,  left_on='match_id',right_on='id' )

In [150]:
batting=mergednew[mergednew['winner']==0]
batting

match_id  target     id           city  winner  win_by_runs  \
247           7     178      7         Mumbai       0            0   
248           7     178      7         Mumbai       0            0   
249           7     178      7         Mumbai       0            0   
250           7     178      7         Mumbai       0            0   
251           7     178      7         Mumbai       0            0   
...         ...     ...    ...            ...     ...          ...   
74409     11414     155  11414  Visakhapatnam       0            0   
74410     11414     155  11414  Visakhapatnam       0            0   
74411     11414     155  11414  Visakhapatnam       0            0   
74412     11414     155  11414  Visakhapatnam       0            0   
74413     11414     155  11414  Visakhapatnam       0            0   

       win_by_wickets  inning         batting_team           bowling_team  \
247                 4       2       Mumbai Indians  Kolkata Knight Riders   
248                 4       2       Mumbai Indians  Kolkata Knight Riders   
249                 4       2       Mumbai Indians  Kolkata Knight Riders   
250                 4       2       Mumbai Indians  Kolkata Knight Riders   
251                 4       2       Mumbai Indians  Kolkata Knight Riders   
...               ...     ...                  ...                    ...   
74409               6       2  Chennai Super Kings         Delhi Capitals   
74410               6       2  Chennai Super Kings         Delhi Capitals   
74411               6       2  Chennai Super Kings         Delhi Capitals   
74412               6       2  Chennai Super Kings         Delhi Capitals   
74413               6       2  Chennai Super Kings         Delhi Capitals   

       ball  total_runs  player_dismissed  
247       1           0                 0  
248       2           0                 0  
249       3           4                 0  
250       4           4                 0  
251       5           5                 0  
...     ...         ...               ...  
74409   110         153                 3  
74410   111         153                 3  
74411   112         153                 4  
74412   113         154                 4  
74413   114         162                 4  

[39554 rows x 13 columns]

In [151]:
mergednew=mergednew.drop(columns=['match_id'])

In [152]:
mergednew=mergednew.drop(columns=['inning'])

In [153]:
mergednew=mergednew.drop(columns=['id'])

In [157]:
batting=mergednew[mergednew['winner']==1]

In [158]:
batting

target       city  winner  win_by_runs  win_by_wickets  \
0         207  Hyderabad       1           35               0   
1         207  Hyderabad       1           35               0   
2         207  Hyderabad       1           35               0   
3         207  Hyderabad       1           35               0   
4         207  Hyderabad       1           35               0   
...       ...        ...     ...          ...             ...   
74533     152  Hyderabad       1            1               0   
74534     152  Hyderabad       1            1               0   
74535     152  Hyderabad       1            1               0   
74536     152  Hyderabad       1            1               0   
74537     152  Hyderabad       1            1               0   

                      batting_team         bowling_team  ball  total_runs  \
0      Royal Challengers Bangalore  Sunrisers Hyderabad     1           1   
1      Royal Challengers Bangalore  Sunrisers Hyderabad     2           1   
2      Royal Challengers Bangalore  Sunrisers Hyderabad     3           1   
3      Royal Challengers Bangalore  Sunrisers Hyderabad     4           3   
4      Royal Challengers Bangalore  Sunrisers Hyderabad     5           7   
...                            ...                  ...   ...         ...   
74533          Chennai Super Kings       Mumbai Indians   116         152   
74534          Chennai Super Kings       Mumbai Indians   117         154   
74535          Chennai Super Kings       Mumbai Indians   118         155   
74536          Chennai Super Kings       Mumbai Indians   119         157   
74537          Chennai Super Kings       Mumbai Indians   120         157   

       player_dismissed  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
...                 ...  
74533                 5  
74534                 5  
74535                 6  
74536                 6  
74537                 7  

[34984 rows x 10 columns]

In [ ]:
mergednew.head()

In [159]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer([
    ('trf', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'city'])
], remainder='passthrough')


In [171]:
mergednew.columns

Index(['target', 'city', 'winner', 'batting_team', 'bowling_team', 'ball',
       'total_runs', 'player_dismissed'],
      dtype='object')

In [169]:
mergednew=mergednew.drop(columns=['win_by_runs','win_by_wickets'])

In [273]:
mergednew['ball']=120-mergednew['ball']

In [ ]:
mergednew['target']=mergednew['target']-mergednew['total_runs']

In [274]:
from sklearn.model_selection import train_test_split
Y=mergednew['winner']
X=mergednew.drop(columns=['winner'])
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=1 )

In [299]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

In [276]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',RandomForestClassifier(n_estimators=20,n_jobs=-1))#D
])

pipe.fit(X_train,y_train)#D

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', RandomForestClassifier(n_estimators=20, n_jobs=-1))])

In [1]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',SVC(kernel='linear'))#D
])

pipe.fit(X_train,y_train)#D

NameError: name 'Pipeline' is not defined

In [296]:
y_pred = pipe.predict(X_test)

In [297]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)#D

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [279]:
pipe.predict_proba(X_test)

array([[0.15, 0.85],
       [0.05, 0.95],
       [0.95, 0.05],
       ...,
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.55, 0.45]])

In [177]:
mergednew.columns

Index(['target', 'city', 'winner', 'batting_team', 'bowling_team', 'ball',
       'total_runs', 'player_dismissed'],
      dtype='object')

In [180]:
X_test.columns

Index(['target', 'city', 'batting_team', 'bowling_team', 'ball', 'total_runs',
       'player_dismissed'],
      dtype='object')

In [292]:
data_to_predict = pd.DataFrame([[120,'Bangalore','Royal Challengers Bangalore', 'Chennai Super Kings', 100, 1, 1]],
                               columns=['target','city', 'batting_team', 'bowling_team', 'ball', 'total_runs', 'player_dismissed'])
data_to_predict['target']=data_to_predict['target']-data_to_predict['total_runs']
data_to_predict['ball']=120-data_to_predict['ball']

In [ ]:
# merged['winner'] = merged.apply(lambda row: 0 if row['batting_team'] == row['winner'] else 1, axis=1)

# array(['Sunrisers Hyderabad', 'Royal Challengers Bangalore',
#        'Kolkata Knight Riders', 'Kings XI Punjab', 'Delhi Capitals',
#        'Mumbai Indians', 'Chennai Super Kings', 'Rajasthan Royals',
#        'Rising Pune Supergiants'], dtype=object)

In [293]:
pipe.predict_proba(data_to_predict)

array([[0.6, 0.4]])

In [265]:
for i in range(1,30):
    pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',RandomForestClassifier(n_estimators=21,n_jobs=-1))#D
   ])

    pipe.fit(X_train,y_train)#D
    p=pipe.predict_proba(data_to_predict)
    print(p+i)

[[1.76190476 1.23809524]]
[[2.80952381 2.19047619]]
[[3.71428571 3.28571429]]
[[4.57142857 4.42857143]]
[[5.66666667 5.33333333]]
[[6.47619048 6.52380952]]
[[7.61904762 7.38095238]]
[[8.61904762 8.38095238]]
[[9.66666667 9.33333333]]
[[10.66666667 10.33333333]]
[[11.57142857 11.42857143]]
[[12.76190476 12.23809524]]
[[13.52380952 13.47619048]]
[[14.61904762 14.38095238]]
[[15.71428571 15.28571429]]
[[16.66666667 16.33333333]]
[[17.52380952 17.47619048]]
[[18.47619048 18.52380952]]
[[19.61904762 19.38095238]]
[[20.66666667 20.33333333]]
[[21.61904762 21.38095238]]
[[22.76190476 22.23809524]]
[[23.61904762 23.38095238]]
[[24.61904762 24.38095238]]
[[25.61904762 25.38095238]]
[[26.61904762 26.38095238]]
[[27.66666667 27.33333333]]
[[28.47619048 28.52380952]]
[[29.47619048 29.52380952]]
